---
title: "Known race and ethnicities across states"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggrepel)
library(cowplot)
knitr::opts_chunk$set(echo = TRUE)
```

## Data

```{r}
kffData <- read.csv('../kff_raw_data.csv', skip = 2) %>% 
  filter(row_number() <= n() - 21) %>% 
  select(-Footnotes) %>% 
  pivot_longer(!Location, names_to="date", values_to="value") %>% 
  separate(date, c('date', 'category'), sep = "__") %>% 
  filter(grepl('Known.Race', category) | grepl('Known.Ethnicity', category)) %>%
  rename(state = Location) %>% 
  mutate(date = as.Date(parse_datetime(date, format = 'as.of.%B.%d..%Y'))) %>% 
  mutate(value = as.numeric(value)) %>% 
  mutate(category = if_else(grepl("Race", category), "race_known", 'ethnicity_known'))

bbgData <- read.csv('../bloomberg/aggregate.csv') %>% 
  mutate(date = as.Date(date)) %>% 
  filter(!is.na(race_known) & date < "2021-03-01") %>% 
  pivot_longer(c('race_known', 'ethnicity_known'), names_to = "category", values_to = "value")

data <- rbind(bbgData, kffData)
```

## Merge with BBG data to get the February perspective

```{r}
data %>% 
  filter(category == 'ethnicity_known') %>% 
  ggplot(aes(date, value, color = category)) +
  geom_line() +
  geom_point() +
  geom_text_repel(aes(label = round(value * 100))) +
  facet_wrap(~ state)
```

## How many states reported R/E data on February 17?

```{r}
bbgData %>% 
  filter(!is.na(value)) %>% 
  pull(state) %>% 
  unique() %>% 
  length()
```




## Figures for the paper

Bar chart of most recent state race known rates
```{r}
gen_state_chart <- function(measure) {
  data %>%
    filter(date == "2021-04-05") %>%
    filter(category == paste0(measure, "_known")) %>%
    arrange(!is.na(value), value) %>%
    mutate(state = factor(state, levels = state)) %>%
    ggplot(aes(state, value)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(
    labels = scales::percent,
    position = "right",
    limits = c(0, 1),
    expand = c(0, 0)
    ) +
    theme(axis.title = element_blank(), plot.margin = unit(c(5.5, 15, 5.5, 0), "points"), axis.text = element_text(size = 10), plot.subtitle = element_text(size = 12)) +
    labs(subtitle = paste0('Percent of vaccination records\nwith ', measure, ' known as of\nApril 5, 2021 by state'))
}

ggsave(
  "../figures/state_measures.png",
  plot_grid(gen_state_chart('race'), gen_state_chart('ethnicity')),
  width = 8,
  height = 9,
  units = "in"
)
```


