name: CDC Vaccination

# Controls when the action will run. 
on:
  # Triggers the workflow every day at 12am EST
  schedule:
    - cron: '0 5 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scrape":
  scrape:
    # The type of computer that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: curl
        uses: wei/curl@master
        with:
          args: -o vaccination_demographics_data/${{ steps.date.outputs.date }}.json https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData\?id\=vaccination_demographics_data
    
      - name: curl
        uses: wei/curl@master
        with:
          args: -o georgia/${{ steps.date.outputs.date }}.html https://dph.georgia.gov/locations/covid-vaccination-site

      - name: curl
        uses: wei/curl@master
        with:
          args: -o texas/${{ steps.date.outputs.date }}.csv https://genesis.soc.texas.gov/files/accessibility/vaccineprovideraccessibilitydata.csv

      - name: curl
        uses: wei/curl@master
        with:
          args: -o louisiana/${{ steps.date.outputs.date }}.json 'https://services5.arcgis.com/O5K6bb5dZVZcTo5M/arcgis/rest/services/Vaccinations_by_Race_by_Parish/FeatureServer/0/query?f=json&where=(Parish%20%3C%3E%20%27Calcasieu%27)%20AND%20(Parish%20%3C%3E%20%27Cameron%27)&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&outSR=102100&resultOffset=0&resultRecordCount=100&resultType=standard'

      - name: curl
        uses: wei/curl@master
        with:
          args: -o louisiana/${{ steps.date.outputs.date }}.pdf https://ldh.la.gov/assets/docs/covid/LACOVIDVACCINE-LOCATIONS.pdf

      # Commit the newly generated data aggregate to this repository (and potentially schema
      # auto-updates like job role groups)
      - name: Commit data aggregate
        uses: EndBug/add-and-commit@v6
        with:
          add: '.'
          message: Vaccine data update via GitHub Actions
